name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:
permissions:
  actions: write
jobs:
  wake-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run wake-up script
        run: python wake_up.py
      - name: Prevent 60-day GitHub Actions Timeout
        uses: gautamkrishnar/keepalive-workflow@v2
